on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - name: compile and release
      uses: wangyoucao577/go-release-action@v1.14
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "cli-paso-a-paso"
        goversion: "https://dl.google.com/go/go1.15.10.linux-amd64.tar.gz"
        ldflags: '-w'
